DROP TABLE IF EXISTS EDGES CASCADE;
DROP TABLE IF EXISTS ROUTES CASCADE;
DROP TABLE IF EXISTS USERS CASCADE; 
DROP TABLE IF EXISTS AIRPORTS CASCADE;
DROP SEQUENCE public.edge_id_seq RESTRICT;
DROP SEQUENCE public.hibernate_sequence RESTRICT;
DROP SEQUENCE public.route_id_seq RESTRICT;
DROP SEQUENCE public.user_id_seq RESTRICT;